language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
  - mv build/index.html build/200.html
deploy:
  provider: surge
  skip_cleanup: true
  domain: lurkershub.surge.sh
  project: ./build/
on:
  branch: master
